### ISSUE TITLE
Incorrect line number reporting in compilation errors when using #include files

### ISSUE THREAD

**Issue by ikadmm** [guimaraeslucas/axonasp#5]
Environment:

    OS: Ubuntu 24.04 LTS
    Web Server: Nginx 1.24
    AxonASP Mode: FastCGI Service
    Legacy Environment: Working perfectly on native IIS 6.0

Describe the bug
When a VBScript compilation error occurs inside an ASP page that implements server-side includes (), the error handler reports an incorrect line number that does not match the source file or the combined script layout.

To help isolate the issue, I created a clean test case that demonstrates exactly how the engine miscalculates the line numbers when an include file is present.
1. Include File: /admin/fragmentos.asp
    Total Length: 183 lines.
    Content: Standard VBScript helper functions (none of which are executed in this test).

2. Main File: /home/test/admin/axon.asp
content:

<%= "Hello Axon! / " %>
<%
On Error GoTo 0

Response.Write "I am going to trigger an error with a previous include / "

Response.Write "Error on line 8:"
a = cInt("a") ' <--- This is physically Line 9 in this file

Response.Write "More lines below"
%>

3. Steps to Reproduce
    Request axon.asp in the browser to force the Type Mismatch runtime error (cInt("a")).
    The browser outputs the following error trace:

Application error
VBScript runtime error error '800A000D'
Type mismatch
File    /home/www/test/admin/axon.asp
**Line    189**
Column  1
Stage   Runtime Error

4. Expected Behavior (Matching Native IIS)
The error handler should report the line number relative to the specific file where the error actually resides, resetting the counter for each file scope.
Since AxonASP correctly identified that the error occurred inside axon.asp, it should report Line 8 or 9 (the actual position within that file), instead of reporting Line 189 (which is an unmapped combination of the include length plus the main file offset).
5. Technical Note on the Bug
Looking at the numbers: 183 (lines from the include file) + 6 (lines executed in the main file after the tag) = 189. The internal parsing engine in Go seems to be concatenating the text tokens globally but forgetting to track and translate individual file line offsets when returning from an #include context back to the parent script.

Thanks for your effort, your project is great!

**Comment by guimaraeslucas** [comment]
I will check this out and improve the implementation! Thanks for reporting the issue.

**Comment by guimaraeslucas** [comment]
The error reporting now correctly identifies the appropriate line and column, accounting for included files, starting from version 2.1.7. Thank you for your report.

**Comment by guimaraeslucas** [comment]
@all-contributors please add @ikadmm for bug
